source('https://www.rubygems.org')

gem('pg')
gem('rspec')
gem('capybara')
gem('sinatra')
gem('sinatra-contrib', :require => 'sinatra/reloader')
gem('sinatra-activerecord')
gem('rake')
gem('guard')
gem('guard-rspec')
gem('launchy')
gem('pry')
